language: node_js
node_js:
  - '10'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - npm ci
script:
  - npm run build.prod
  - npm run test.ci
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
