language: node_js
node_js:
  - '10'
addons:
  chrome: stable
install:
  - npm ci
script:
  - npm run lint
  - npm run test.ci
  - npm run build.prod
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
